# Jekyll 配置文件
title: "Jay Feng`s Blog"
description: "探索代码的无限可能，分享技术的前沿思考"
author: "Jay"
email: "fz.dev@foxmail.com"
baseurl: ""
url: "https://ruijayfeng.github.io"

# 构建设置
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

# 插件 (GitHub Pages 支持的插件)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

# 代码高亮设置
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false

# 分页设置
paginate: 6
paginate_path: "/page:num/"

# 社交媒体链接
social:
  github: "ruijayfeng"
  twitter: "ruizhefeng"
  linkedin: "JayFeng"

# 网站设置
timezone: Asia/Shanghai
lang: zh-CN